# This file was generated by GoReleaser. DO NOT EDIT.
cask "whodar" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "975c8f4b99d3698fd779c4df84a66b2b5cb25143bbde9c29a192deb1612fd255"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9218e4999ae72f963e0593e12026218660ab24c1938cb136b20530d9430be881"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "505e3d8b7e30c660528ee4dda83452e3e5b70576ffda2fe94374230d0d9091b8"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eaf3d86b76c9df9a957886f3017e1b6d7686ce148e2f0aca12d626c25639f2ac"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "whodar"
  desc "Know who knows. Find who to talk to about X across your work tools."
  homepage "https://github.com/dcadolph/whodar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whodar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whodar"]
    end
  end

  # No zap stanza required

end
