# This file was generated by GoReleaser. DO NOT EDIT.
cask "whodar" do
  version "0.1.10"

  on_macos do
    on_intel do
      sha256 "ca8303fad235e4110cf1c918705c1ca1617946a7b5ba7c84cbed3d85c182f43c"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "96a104f8df28bc99adc51ced238c77c1e0854c68816c78ab2912376f7f0385c5"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ca00bef1c26e70b77e5707c5b0a5621ed4e5c98deaa2e5949e85e6f3f40a8e5"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "106854f00a5cd8289cbf1a9b1df8f55b0f4ff744ef847963dd633ae5298cff61"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "whodar"
  desc "Know who knows. Find who to talk to about X across your work tools."
  homepage "https://github.com/dcadolph/whodar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whodar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whodar"]
    end
  end

  # No zap stanza required

end
