# This file was generated by GoReleaser. DO NOT EDIT.
cask "whodar" do
  version "0.1.18"

  on_macos do
    on_intel do
      sha256 "0b32e9903d1b72a3a599aee3ba557fde90661aa7fa202c9a604307d5f307c151"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7de1c6c5cb75c8156305efd1af29e9a16f453fc332d9934a7a0a9c6c7f178506"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "be21ce824a4321af668076b06ee115931bbbb38b21eb700bf21b49c449f68060"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fc36bc4011912bb9e4388cc898d453d190780a73048d7da378d9d4037cdbd9dc"
      url "https://github.com/dcadolph/whodar/releases/download/v#{version}/whodar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "whodar"
  desc "Know who knows. Find who to talk to about X across your work tools."
  homepage "https://github.com/dcadolph/whodar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whodar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whodar"]
    end
  end

  # No zap stanza required

end
